### PR TITLE
Docker: rewrite to be more path-based routing friendly

### PR DESCRIPTION
**Pull request by xabolcs**
See openseedbox/openseedbox#82

### CODE REVIEW

**Comment by xabolcs** [comment]
This works for me nicely on `aarch64`.

@gregorkistler , wanna give it a try?

**Comment by gregorkistler** [comment]
> This works for me nicely on `aarch64`.
> 
> @gregorkistler , wanna give it a try?

Works for me as well. Didn't see any issues 👍

**Comment by xabolcs** [comment]
Thanks!

I'll merge it today! :+1:

**Comment by xabolcs** [comment]
**xabolcs** merged commit 1c3d54d06210972ca551cb91f6ada30e18a8ffa7 into `openseedbox:master` [1 minute ago](https://github.com/openseedbox/openseedbox-server/pull/7#event-7051609898) :sweat_smile:

**Pull request merged**
