### PR TITLE
Fixed typo in the index.html URL and changed df --block-size to df -B…

### PR DESCRIPTION
**Pull request by gregorkistler**
… in Status.java because Alpine doesn`t support the long option.

Tested also with Ubuntu, CentOS, PhotonOS and CoreOS

### CODE REVIEW

**Comment by xabolcs** [comment]
Please do not use the `https` as it causes cert validation error!
```
www.openseedbox.com uses an invalid security certificate. The certificate is only valid for the following names: www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com

Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

**Comment by xabolcs** [comment]
And also apply the change for the readme too! Thanks!

**Comment by gregorkistler** [comment]
The used protocol wasn´t changed. The current index.html already makes use of https. I just added a missing 'd' to the word 'openseedbox'.

Of course I could change it also to https://github.com/openseedbox/openseedbox-server or https://github.com/openseedbox/openseedbox (to comply with the Readme.md which Erin change within the last days) if needed, otherwise I adjust only the protocol.

**Comment by xabolcs** [comment]
I see. Fix the address as `www.openseedbox.com` and change the protocols to `http`, please.

**Comment by xabolcs** [comment]
@gregorkistler , shoud I wait for any feedback from you, or may I merge this as is?

**Comment by gregorkistler** [comment]
Sorry for being late. I´ve updated the PR. Should be safe to merge now.

**Comment by xabolcs** [comment]
Thanks! :+1:

**Pull request merged**
